Controllers/ContabilitateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LKW_Bursa_Transport.Areas.Identity.Data;
using LKW_Bursa_Transport.Models;
using Microsoft.AspNetCore.Identity;

namespace LKW_Bursa_Transport.Controllers
{
    public class ContabilitateController : Controller
    {
        private readonly AuthDbContext _context;

        private readonly UserManager<ApplicationUser> _userManager;

        public ContabilitateController(AuthDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        // GET: Contabilitate
        public async Task<IActionResult> Index()
        {
            var user = _userManager.GetUserAsync(User).Result;

            var cont = from c in _context.Contabilitate
                           .Include(v => v.Companie)
                           .Where(c => c.CompanieID == user.Id)
                           select c;

            return View(await cont.AsNoTracking().ToListAsync());
        }

        public async Task<IActionResult> AdaugaCursa(int? id)
        {

            Cursa cursaPreluata = await _context.Curse
                .Include(cursa => cursa.Ruta)
                .AsNoTracking()
                .FirstOrDefaultAsync(c => c.CursaID == id);

            if (cursaPreluata == null)
            {
                return NotFound();
            }

            var user = _userManager.GetUserAsync(User).Result;

            var contabilitate = await _context.Contabilitate
                .Include(c => c.Companie)
                .FirstOrDefaultAsync(m => m.CompanieID == user.Id);

            contabilitate.Venit += cursaPreluata.Pret;

            if (contabilitate.CurseEfectuate == null)
            {
                contabilitate.CurseEfectuate = new List<Cursa>();
            }

            contabilitate.CurseEfectuate.Add(cursaPreluata);
            
            await _context.SaveChangesAsync();

            return View(contabilitate);
        }

        // GET: Contabilitate/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contabilitate = await _context.Contabilitate
                .Include(c => c.Companie)
                .FirstOrDefaultAsync(m => m.ContabilitateID == id);
            if (contabilitate == null)
            {
                return NotFound();
            }

            return View(contabilitate);
        }

        // GET: Contabilitate/Create
        public IActionResult Create()
        {
            ViewData["CompanieID"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: Contabilitate/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ContabilitateID,Venit,Cheltuieli,CompanieID")] Contabilitate contabilitate)
        {
            if (ModelState.IsValid)
            {
                _context.Add(contabilitate);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CompanieID"] = new SelectList(_context.Users, "Id", "Id", contabilitate.CompanieID);
            return View(contabilitate);
        }

        // GET: Contabilitate/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contabilitate = await _context.Contabilitate.FindAsync(id);
            if (contabilitate == null)
            {
                return NotFound();
            }
            ViewData["CompanieID"] = new SelectList(_context.Users, "Id", "Id", contabilitate.CompanieID);
            return View(contabilitate);
        }

        // POST: Contabilitate/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ContabilitateID,Venit,Cheltuieli,CompanieID")] Contabilitate contabilitate)
        {
            if (id != contabilitate.ContabilitateID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(contabilitate);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContabilitateExists(contabilitate.ContabilitateID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CompanieID"] = new SelectList(_context.Users, "Id", "Id", contabilitate.CompanieID);
            return View(contabilitate);
        }

        // GET: Contabilitate/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contabilitate = await _context.Contabilitate
                .Include(c => c.Companie)
                .FirstOrDefaultAsync(m => m.ContabilitateID == id);
            if (contabilitate == null)
            {
                return NotFound();
            }

            return View(contabilitate);
        }

        // POST: Contabilitate/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var contabilitate = await _context.Contabilitate.FindAsync(id);
            _context.Contabilitate.Remove(contabilitate);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ContabilitateExists(int id)
        {
            return _context.Contabilitate.Any(e => e.ContabilitateID == id);
        }
    }
}

Controllers/RuteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LKW_Bursa_Transport.Areas.Identity.Data;
using LKW_Bursa_Transport.Models;

namespace LKW_Bursa_Transport.Controllers
{
    public class RuteController : Controller
    {
        private readonly AuthDbContext _context;

        public RuteController(AuthDbContext context)
        {
            _context = context;
        }

        // GET: Rute
        public async Task<IActionResult> Index()
        {
            return View(await _context.Rute.ToListAsync());
        }

        // GET: Rute/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ruta = await _context.Rute
                .Include(ruta => ruta.Curse)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.RutaID == id);
            if (ruta == null)
            {
                return NotFound();
            }

            return View(ruta);
        }

        // GET: Rute/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Rute/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RutaID,TaraIncarcare,TaraDescarcare")] Ruta ruta)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ruta);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ruta);
        }

        // GET: Rute/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ruta = await _context.Rute
                .FirstOrDefaultAsync(m => m.RutaID == id);
            if (ruta == null)
            {
                return NotFound();
            }

            return View(ruta);
        }

        // POST: Rute/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ruta = await _context.Rute.FindAsync(id);
            _context.Rute.Remove(ruta);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RutaExists(int id)
        {
            return _context.Rute.Any(e => e.RutaID == id);
        }
    }
}

Views/Rute/Create.cshtml
@model LKW_Bursa_Transport.Models.Ruta

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section head{
    <style type="text/css">
        body {
            background-image: url('../../back.jpg');
            background-repeat: no-repeat;
            background-size: cover;
        }
    </style>
}
<h1>Adauga ruta noua</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TaraIncarcare" class="control-label"></label>
                <input asp-for="TaraIncarcare" class="form-control" />
                <span asp-validation-for="TaraIncarcare" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TaraDescarcare" class="control-label"></label>
                <input asp-for="TaraDescarcare" class="form-control" />
                <span asp-validation-for="TaraDescarcare" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Adauga" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Inapoi la lista de rute</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Rute/Delete.cshtml
@model LKW_Bursa_Transport.Models.Ruta

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section head{
    <style type="text/css">
        body {
            background-image: url('../../back.jpg');
            background-repeat: no-repeat;
            background-size: cover;
        }
    </style>
}

<h1>Stergere</h1>

<h3>Esti sigur ca vrei sa stergi aceasta ruta?</h3>
<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TaraIncarcare)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TaraIncarcare)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TaraDescarcare)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TaraDescarcare)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="RutaID" />
        <input type="submit" value="Stergere" class="btn btn-danger" /> |
        <a asp-action="Index">Inapoi la lista cu rute</a>
    </form>
</div>

Views/Rute/Details.cshtml
@model LKW_Bursa_Transport.Models.Ruta

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section head{
    <style type="text/css">
        body {
            background-image: url('../../back.jpg');
            background-repeat: no-repeat;
            background-size: cover;
        }
    </style>
}
<h1>Curse Disponibile</h1>

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TaraIncarcare)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TaraIncarcare)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TaraDescarcare)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TaraDescarcare)
        </dd>


        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Curse)
        </dt>
        <dd class="col-sm-10">
            <table class="table">
                <tr>
                    <th>Oras Incarcare</th>
                    <th>Oras Descarcare</th>
                    <th>Km</th>
                    <th>Pret</th>
                </tr>
                @foreach (var item in Model.Curse)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.OrasIncarcare)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.OrasDescarcare)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Km)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Pret)
                        </td>
                        <td>
                            <a asp-controller="Contabilitate" asp-action="AdaugaCursa" asp-route-id="@item.CursaID">Accepta Cursa</a>
                        </td>
                    </tr>
                }
            </table>
        </dd>


    </dl>
</div>
<div>
    <a asp-action="Index">Inapoi la  rute</a>
</div>

Views/Rute/Index.cshtml
@model IEnumerable<LKW_Bursa_Transport.Models.Ruta>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section head{
    <style type="text/css">
        body {
            background-image: url('../../back.jpg');
            background-repeat: no-repeat;
            background-size: cover;
        }
    </style>
}

<p>
    <a asp-action="Create">Adauga ruta noua</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TaraIncarcare)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TaraDescarcare)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TaraIncarcare)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TaraDescarcare)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.RutaID">Vezi curse disponibile</a> |
                    <a asp-action="Delete" asp-route-id="@item.RutaID">Stergere</a>
                </td>
            </tr>
        }
    </tbody>
</table>